X2: manifest: set target-level 3
stderr:getKernelLevel: Both device manifest and kernel release do not specify kernel FCM version.
getKernelLevel: Both device manifest and kernel release do not specify kernel FCM version.
Both device manifest and kernel release do not specify kernel FCM version.
getKernelLevel:
ERROR: files are incompatible: android.hardware.gnss@1.0::IGnss/default is deprecated in compatibility matrix at FCM Version 4; it should not be served.
android.hardware.gnss@1.0::IGnss/default is deprecated in compatibility matrix at FCM Version 4; it should not be served.: Success

Signed-off-by: Sukrut4778 <sukrut4778@gmail.com>